### ISSUE TITLE
재밌네요

### ISSUE THREAD

**Issue by Hyung1Jung** [DunDung/campus-life-portfolio#1]
- 전승익

**Comment by DunDung** [comment]
???ㅋㅋㅋ언제봤대ㅋㅋ  미완성입니다.

**Comment by DunDung** [comment]
![출입증수정본](https://user-images.githubusercontent.com/33235211/114611237-c877d700-9cdb-11eb-9bb4-42b04c9a19d6.jpg
![출입증수정본](https://user-images.githubusercontent.com/33235211/114612294-ee51ab80-9cdc-11eb-971a-a8de1e09d827.jpg)
)


![image](https://user-images.githubusercontent.com/33235211/114613424-489f3c00-9cde-11eb-8209-8fcd6923c6cb.png)
![image](https://user-images.githubusercontent.com/33235211/114615338-8735f600-9ce0-11eb-9dae-ffdd94b59bd3.png)

**Comment by Hyung1Jung** [comment]
승익이가 자기와의 추억을 안써주어서 넘 섭섭하데

**Comment by DunDung** [comment]
승익이에게 물어봐볼게 ㅎ
